### ISSUE TITLE
minecraft crashed when littlemaid get in the boat

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#1]
minecraft crashed when littlemaid get in boat when useing littleMaidMob-Chloe2-190 texture pack ,
but it didnt crashed when use default texture.
can it be fixed?

[crash-2019-11-21_03.15.12-client.txt](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/3870879/crash-2019-11-21_03.15.12-client.txt)

**Comment by firis-games** [comment]
littleMaidMob-Chloe2-190を含むnet.blacklab.lmr.entity.EntityLittleMaidを利用しているモデルがエラーが発生する場合があります。
暫定対応としてnet.blacklab.lmr.entity.EntityLittleMaidを利用していても落ちないようにMod本体へ代替クラスを追加し対応します。対応版はver.fp.010でリリース予定です。

commit: fe44885678e78ebdfe3ea935aaf79b4f7779a8c7
