### ISSUE TITLE
雪玉を打つメイドの音声問題

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#11]
LMRFPメイドの雪だるま式の声はNO DAMAGE.OGGであり、1.10.2LMRバージョンの声はSNOW DAMAGE.OGGです。

**Comment by firis-games** [comment]
雪合戦ダメージの判定処理を変更しhurt_snowを利用するように修正しました。
対応版はver.fp.022でリリース予定です。

commit: 91f2251dddc69592fc7ca59c79b7c1411e7def94
