### ISSUE TITLE
他のメイドは着席アニメーションを間違って持っている

### ISSUE THREAD

**Issue by UnclassifiedX** [firis-games/LittleMaidReengagedFirisPatch#12]
デフォルトモデルには正しいアニメーションがありますが、modchuモデルなどの他のモデルには異なるアニメーションがあります。 提供された画像の「その他」は、他のLittlemaidModです(https://user-images.githubusercontent.com/61331732/76032749-8c831780-5f08-11ea-9676-4a234352c4f3.png)

**Comment by firis-games** [comment]
動作がおかしいものを報告する場合は細かい条件を記載して下さい。
今回の場合は、下記の通りです。
・動作確認に使用したMinecraftForgeとLittleMaidReengaged Firis's Patchのバージョン
・「その他」で確認したMinecraftForgeとLittleMaidMobのバージョンと作者
・使用したマルチモデルの正式名称
特にLittleMaidMobは複数の作者による複数のバージョンが存在しているためどの作者とバージョンがどれなのかを具体的に記載して下さい。またマルチモデルがすでに入手不可能なものの場合は対応できません。

**Comment by firis-games** [comment]
追加情報はないようですのでこの件は完了とします。
