### ISSUE TITLE
リトルメイドのスキンの非対応

### ISSUE THREAD

**Issue by Hakurenge** [firis-games/LittleMaidReengagedFirisPatch#13]
Minecraft version 1.12.2 forge1.12.2-14.23.5.2838
LittleMaidReengaged-unofficialにて配布されているvoms様の作ったマルチモデル
littleMaidMob-Beverly7-1.11.zip
littleMaidMob-Chloe2-1.11.zip
littleMaidMob-Elsa5-1.11.zip
を導入したところテクスチャがぐちゃぐちゃになる現象が発生しました。
ＭＯＤ最新バージョン(LittleMaidReengaged Firis's Patch ver.fp.023)
にて確認済みです。

**Comment by Hakurenge** [comment]
![2020-03-08_17 56 00](https://user-images.githubusercontent.com/61931976/76159673-33b0ba80-6166-11ea-8d40-0cb5ca83d3c8.png)

**Comment by firis-games** [comment]
LMRFPはlittleMaidMob-Beverly7、littleMaidMob-Chloe2、littleMaidMob-Elsa5の1.11版ではなく1.9版に対応しています。
1.11版は想定していないモデルですが処理自体にモデルIDとテクスチャIDの指定の小文字大文字の処理で想定外の部分があったため対応しています。
対応版はver.fp.024でリリース予定です。

commit: 8fa03cd2ff3ab7600f3f9f89c33906b33fb0a16b
