### ISSUE TITLE
木こりモードでインベントリ内の斧から消費される

### ISSUE THREAD

**Issue by nyapeza** [firis-games/LittleMaidReengagedFirisPatch#14]
LittleMaidReengaged version 8.1.6.141.fp.023
Minecraft version 1.12.2-forge1.12.2-14.23.5.2847

ご多忙とは思いますが、
正しい挙動であるかどうか判断できなかったので、ここに書き込ませていただきます。
メイドさんの手に鋏等耐久度のあるツールを持たせ、メイドインベントリにも鋏を入れて作業させると手に持ったツールの耐久度が減りますが、

木こりモードで同様に作業させたところ、
OFFハンドに斧をセットした場合だと、そのまま手に持って反映されますが、
利き手に木の斧をセットしたところ、木の斧ではなく、メイドインベントリ内のダイヤの斧を持って作業し、耐久度もインベントリ内のダイヤの斧から減っていました。
又、インベントリ内の斧を外すと、利き手のスロットと手に持った斧が消失し、空の利き手スロットをクリックすると斧のアイコンが復活します。（その間も斧を持っている判定のようですので素手の格好で木こり続けます）
この為、利き手に斧以外の職業の割り当てのないアイテムを持たせても木こりの小娘のままになったりすることもあります。

再現が必要でしたら細かい環境を書き込ませていただきます。
致命的な問題ではありませんので、お手すきの時がありましたらご確認よろしくお願いします。

**Comment by firis-games** [comment]
メイドさんのメインハンドに職業アイテムをセットした場合にメインハンドのアイテムが優先されるように変更しました。
トリガー以外のアイテムを持たせた場合に通常モードにリセットするように変更しました。

対応版はver.fp.024でリリース予定です。

commit: 7a157c05839da2a8f7a6d2635add822a40975e60
