### ISSUE TITLE
アーチャーモードで攻撃するとメイドはテレポートしない

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#15]
アーチャーモードがモンスターを攻撃するとき、ターゲットが遠すぎる場合、メイドはその場に留まり、メイドはプレイヤーにテレポートしません。

**Comment by firis-games** [comment]
戦闘中にメイドさんを呼び戻したい場合は[/maid call all]のコマンドでテレポートさせて下さい。
