### ISSUE TITLE
毛刈りメイドさんがチェストに格納してくれない

### ISSUE THREAD

**Issue by nyapeza** [firis-games/LittleMaidReengagedFirisPatch#17]
LittleMaidReengaged Firis's Patch ver.fp.024

自由行動の木こり・自由人・農家・毛刈りモードで試してみたところ、
毛刈りモードのメイドさんがインベントリにアイテムがいっぱいになってもチェストに収納してくれません。
チェストに格納してくれない条件があるのでしょうか？

**Comment by firis-games** [comment]
毛刈りメイドさんは元々チェストへの格納はしないようになっています。
今回毛刈りモードにも運び屋モードを追加しました。

毛刈りメイドさんの運び屋モードの追加版はver.fp.025でリリース予定です。

commit: 428228fb364c400cfc82fbb6896360dfd28817ea
