### ISSUE TITLE
Can't add Tinkers' Construct range weapon to Archer mode

### ISSUE THREAD

**Issue by scikirbypoke** [firis-games/LittleMaidReengagedFirisPatch#18]
Tried add their item id to config file, not working. The trigger item registerer seems can't register anything too.

**Comment by firis-games** [comment]
Modのアイテム登録タイミングのよって設定ファイルのtriggerがうまく反映されない問題が発生する場合があります。trigger登録のタイミングをpreInitからinitへ変更しました。

対応版はver.fp.025でリリース予定です。

commit: ac49a5cfcfd8bea81eb9bae6e35572f2868a5b1a
