### ISSUE TITLE
中立的なモンスターの攻撃はメイドを傷つけません

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#19]
メイドが複数のゾンビピッグマンを攻撃した場合、メイドに攻撃されたゾンビピッグマンのみがメイドにダメージを与え、他のゾンビピッグマン攻撃はメイドにダメージを与えません。 GrimoireOfGaia3など、他のMODの中立モンスターにもこの問題があるようです。 これはバグですか？

**Comment by firis-games** [comment]
メイドさんがリンクするモブに対してターゲット以外から攻撃を受けない問題に対応しました。

対応版はver.fp.025でリリース予定です。

commit: 9d546e0a84bc34297a1f3f484ff90feb472d2910
