### ISSUE TITLE
archer mode aiming angle is too low

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#2]
littlemaid archer mode angle of aim is too low to attack enemies at heights.if a Ghast on top of littlemaid,her can't attack it.

**Comment by firis-games** [comment]
弓兵メイドさんは真上に近い位置に敵Mobがいる場合、メイドさんはうまく攻撃はできません。これは以前のバージョンから同じ挙動になります。旧バージョンでは弓の射線が完全に通った場合のみ矢を撃っていますがこのバージョンではその判定を緩くしているため無駄撃ちが発生しています。致命的な不具合ではないため、現時点では対応時期は未定です。

**Comment by firis-games** [comment]
弓兵メイドさんは真上に近い位置に敵Mobがいる場合、メイドさんはうまく攻撃はできません。これは以前のバージョンから同じ挙動になります。旧バージョンでは弓の射線が完全に通った場合のみ矢を撃っていますがこのバージョンではその判定を緩くしているため無駄撃ちが発生しています。致命的な不具合ではないため、対応するかは未定です。

**Comment by erer00gg** [comment]
ok,thank you
