### ISSUE TITLE
黄昏の森のエリアロック内のmob攻撃不可

### ISSUE THREAD

**Issue by roxas1533** [firis-games/LittleMaidReengagedFirisPatch#20]
黄昏の森(twilightforest-1.12.2-3.10.1013)にてエリアロックがかかっているmobに対してメイドの攻撃が当たらない状況です。(プレイヤー自身は進捗達成により攻撃できます）メイドそのものに進捗がないためであると思われます。

**Comment by firis-games** [comment]
メイドさんの攻撃の際にプレイヤーと同様に進捗によるダメージ制限があるようです。
メイドさんの進捗を取得する際にご主人さまの進捗を取得するように変更しました。
この対応によりメイドさんがご主人さまが進捗を達成している場合に黄昏の森側の攻撃保護機能を回避することができます。

対応版はver.fp.025でリリース予定です。

commit: 38e300bc4cadf2c8938854e97af4df4720f48d83
