### ISSUE TITLE
メイドは戦いで盾でブロックできますか？

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#21]
MC1.6-1.7のLittlemaidMobのメイドは、戦闘中に剣でブロックします。 MC1.12.2の剣はブロックする能力を失いましたが、FirisPatchバージョンでは、メイドがブロックするためにシールドを着用できますか？

**Comment by firis-games** [comment]
LittleMaidReengaged Firis's Patchではメイドさんが盾で攻撃をブロックする機能を追加する予定はありません。
