### ISSUE TITLE
ChocolateQuestRepouredモンスターの近接攻撃はメイドを傷つけません

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#22]
すべてのChocolateQuestRepouredモンスターの近接攻撃は、メイドを傷つけません。
使用されたMod：ChocolateQuestRepoured-1.12.2-1.12.2A
LittleMaidReengaged_FirisPatch-8.1.6.141.fp.025

**Comment by firis-games** [comment]
メイドさんの攻撃はプレイヤーに偽装され発生します。ChocolateQuestRepouredのモンスターは偽装したプレイヤーへ攻撃をしかけるため、メイドさんへの攻撃が成功しません。他のModのMobで問題ないのはModのつくりによる問題です。

メイドさんのプレイヤーの偽装しての攻撃処理を変更し、モブの攻撃として処理するように変更しました。これにより反撃のターゲッティングが正常に動作するようになります。
但しプレイヤーによる攻撃のみでしかダメージが与えられない敵に関してメイドさんの攻撃が通らなくなります。

対応版はver.fp.026でリリース予定です。

commit: 7f1e938961f7b0a5f6c6e068d49be10010c84c75
