### ISSUE TITLE
Sorry I can't get the sound to work.

### ISSUE THREAD

**Issue by Trancescender** [firis-games/LittleMaidReengagedFirisPatch#23]
I put the sound files with the sounds.json. I get no sounds.
File method looks like this. 
  (littleMaidMod_ONE_v102.zip -> .minecraft(.technic) / mods / littlemaidsreengage / unzip / no sound.
   
![2020-03-23 (1)](https://user-images.githubusercontent.com/62537523/77293493-8da0ab00-6d36-11ea-9140-2fc276f4d29f.png)
![2020-03-23](https://user-images.githubusercontent.com/62537523/77293497-8ed1d800-6d36-11ea-97cf-f77ed59844a8.png)

Sorry to bother you.

**Comment by firis-games** [comment]
サウンドパックの導入方法がver.fp.029より変更されています。
サウンドパックファイルをzipファイルのままmodsフォルダへ導入しmods/LittleMaidResource/setting_custom_sounds.jsonで音声を設定して下さい。
