### ISSUE TITLE
Suggestions about archer mode and maid avatar

### ISSUE THREAD

**Issue by scikirbypoke** [firis-games/LittleMaidReengagedFirisPatch#24]
First, vanilla minecraft 1.12 have many high value potion arrows. If they were shot to ground by a maid, they can be picked up by player to get free duplicates. Maybe you can add a config option to disable these arrow's pickability?
Second, players in maid avatar can sit down, but player's view point would not change. Maybe you can add this feature.
Third, maids can use bows and crossbows from Tinkers' Construct, but cannot use it's ammos. I figure out it was because `EntityLittleMaidAvatarMP` did not implement `hasCapability` and `getCapability` while TiC is searching for `CapabilityItemHandler.ITEM_HANDLER_CAPABILITY`. TiC's code can be found [here](https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/library/utils/AmmoHelper.java). I added these two function on my local fork, and it worked. Maybe you can try to implement them correctly to fix the problem.
Fourth, maids can hurt other maids, which sometimes let them kill each other easily. Maybe you can find a way to fix this?
Fifth, I found some code in maid's AI attempted to adapt different kinds of range weapons. I think add a new condition to adapt straight line trajectory weapon(such as laser guns from [Plustic](https://minecraft.curseforge.com/projects/plustic)) may be a good idea.
Finally, currently archer mode maids judge if they can attack by looking for if both arrows and bows exist in inventory. But some range weapons from other mods(e.g. shurikens and laser guns) did not need ammos. Maybe you can add a configurable list to contain this kind of items, so they may enable maid attack alone.

**Comment by firis-games** [comment]
No.1
矢が増殖する問題はプレイ上支障がでるものではないため優先度は低いです。
拾った矢が不要な場合は捨てるなどして自身で対応して下さい。

No.2
リトルメイドアバターのモーション機能は見た目だけのものです。
視線調整が行われていないのは仕様です。

No.3 No.5
他Modとの連携は必要に応じて行うため優先度は低いです。
ソース改変、再利用等はLICENCEを遵守していれば好きに利用可能です。
必要であればご自身のローカルで改変したModをご利用下さい。

No.4
フレンドリーファイアに関する調整は未定です。
必要であれば同等機能を持ったModを導入するなどで対応して下さい。

No.6
弾薬を使用しない射撃武器を設定する場合はarcher.S:Arrowに武器のアイテムIDを登録して下さい。
これで利用可能であればメイドさんが射撃武器を使用します。

**Comment by scikirbypoke** [comment]
Thank you for your response. But `ITEM_HANDLER_CAPABILITY` is not used to interact with single mod, it is a compatibility statement allows mods to check entity's inventory in a way not causing crashes. I have found 6 open source mods check this capability on entities, so adding it will make LMR have compatibility with more mods. If you still don't want to add this capability now, can I make a pull request to do it?
