### ISSUE TITLE
MaidAvatarとGVC銃器の問題。

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#25]
プレイヤーがMaidAvatarになり、GVC銃を入手すると、3人称の表示がおかしくなります。
MODの使用：HMGDollsFrontLine1.12.2.β.11.0
LittleMaidReengaged_FirisPatch-8.1.6.141.fp.026
GVCLib__1.12.2__1.7

**Comment by firis-games** [comment]
三人称視点で銃が描画されないのは、リトルメイドアバターとLittleMaidGVCAddonと現時点で連携していないためです。リトルメイドアバターとLittleMaidGVCAddonの連携処理は今後追加予定です。
