### ISSUE TITLE
スキン変更でクラッシュ

### ISSUE THREAD

**Issue by abc-appy** [firis-games/LittleMaidReengagedFirisPatch#26]
メイドさんのスキンの変更画面に入ろうとするか、インベントリから矢印で何度か直接変更しようとするとクラッシュします。
PFLMのデフォルトスキンパックのみ導入した状態です。

Forge 1.12.2 - 14.23.5.2768
![無題](https://user-images.githubusercontent.com/63005937/78156369-ad904700-7479-11ea-8fec-9121e57d2d4f.png)

[crash-2020-04-02_00.18.28-client.txt](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/4416197/crash-2020-04-02_00.18.28-client.txt)

**Comment by firis-games** [comment]
メイドモデル描画時にPFLMモデルでエラーが出る問題に対応しました。

対応版はver.fp.027でリリース予定です。

commit: 2acc93ff2b886bc489e7ca59bf5ca618d5b856c0
