### ISSUE TITLE
リトルメイドの挨拶の声についてのいくつかの提案

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#32]
以前のバージョンでは、リトルメイドの「おはよう」と「こんばんは」（プレーヤーの睡眠の前後の「おやすみ」や「おはよう」の声ではありません）の声は、在庫に時計がある場合にのみ挨拶します。 在庫に時計がない場合、リトルメイドは1日を通して「living_daytime」とだけ言います。 バージョンfp.029から、インベントリに時計があるかどうかにかかわらず、すべてのリトルメイドが挨拶し、おはよう挨拶は長くありませんが、夜になると、すべてのリトルメイド（野生を含む）が夜明けまで「こんばんは」を繰り返します。 夜の声が単調すぎる？

質問1：以前のバージョンと同じにすることはできますか？リトルメイドはインベントリに時計があるときだけ挨拶します。

質問2：そうでない場合、リトルメイドは夕方の特定の時間、たとえば午後6時から午後7時まで挨拶できますか？

**Comment by firis-games** [comment]
living_morningとliving_nightの条件を時計所持時の朝と夜のliving_daytimeの代わりにしゃべるように変更しました。音声の仕様については今度も変更する場合があります。

変更版はver.fp.037でリリース予定です。

commit: 43633a65cbd9eb0df2078521c0dce99b6ad8b4ba
