### ISSUE TITLE
maid can't move after using Mob Bottle

### ISSUE THREAD

**Issue by oilcash01** [firis-games/LittleMaidReengagedFirisPatch#34]
https://www.picz.in.th/image/2020-05-04-164212.UsuPBQ

**Comment by firis-games** [comment]
現象が発生し際のMinecraftForgeのバージョン、LMRFPのバージョン、MobBottleのバージョン、再現手順を明記して下さい。
通常手順で確認したところこちらでは現象を確認できません。

**Comment by oilcash01** [comment]
https://www.picz.in.th/image/U2rQzZ
https://www.picz.in.th/image/U2rURI
https://www.picz.in.th/image/U2rq6P
https://www.picz.in.th/image/U2rEWt

iremoved mobBottle and updated forge and java to lasted version(1.12.2 - 14.23.5.2847). and i tested use Spawn Egg and rejoin the game.

P.S. : sorry i'm bad english and japan language. i use translate

**Comment by firis-games** [comment]
類似現象を対応しましたので次のバージョンで確認してください。
同じ問題が発生しましたら別途報告して下さい。

対応版はver.fp.036でリリース予定です。

commit: 5497d8544f74b52742ca6c460da5eeef8787a217
