### ISSUE TITLE
リトルメイドの視点には問題があります

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#36]
fp.037バージョンのリトルメイドの視角が間違っているプレーヤーや他の生き物を見ると、リトルメイドの視界が高すぎます。 ゲームに再び入るかリトルメイドが死んだ後、通常の視点が復元されます。
![2020-05-10_04 42 50](https://user-images.githubusercontent.com/58005561/81483826-ef33bf00-927b-11ea-9a74-6ab36c5ffa6b.png)
![2020-05-10_04 42 39](https://user-images.githubusercontent.com/58005561/81483831-f3f87300-927b-11ea-90d8-b68f2ebbfbf1.png)

**Comment by firis-games** [comment]
モデル変更時にサーバーサイドのモブサイズを変更するように対応しました。
対応版はver.fp.038でリリース予定です。

commit: 33a35ebb8f79aad72d2e3285da43451fe74f742c
