### ISSUE TITLE
リトルメイドは近接攻撃を行うことができません

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#37]
fp.037のリトルメイドは近接攻撃を実行できず、リトルメイドはクリーチャーを攻撃しません。
![2020-05-10_04 52 58](https://user-images.githubusercontent.com/58005561/81483928-9add0f00-927c-11ea-813a-35331b64f914.png)
![2020-05-10_04 53 51](https://user-images.githubusercontent.com/58005561/81483930-9dd7ff80-927c-11ea-8466-6dcda2efa3bf.png)

**Comment by firis-games** [comment]
近距離のターゲッティングが正常に動作するように対応しました。
対応版はver.fp.038でリリース予定です。

commit: 5ff66b123df298e0c888180bc4d28ddfdbb3a201
