### ISSUE TITLE
リトルメイドスキンパックに関する質問

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#39]
ワイルドリトルメイドのスキンパックについては、バージョンfp.033ではワイルドリトルメイドのテクスチャが異なります（例：littleMaidMob-Chloe2-190）。 しかしfp.038では、野生のリトルメイドのテクスチャは飼いならされたリトルメイドと同じになります。 このバグを修正する予定はありますか？

fp.033
![20200513-133742337_20200513134117](https://user-images.githubusercontent.com/58005561/81771962-7b194580-951f-11ea-80e3-593d2c4283e6.gif)

fp.038
![20200513-133258722_20200513133932](https://user-images.githubusercontent.com/58005561/81772003-95532380-951f-11ea-9380-0de96b635d04.gif)

**Comment by firis-games** [comment]
野生テクスチャが無効になっていました。
野生テクスチャを有効にするように対応しました。
対応版はver.fp.039でリリース予定です。

commit: 3230a68a2fb635a1754bc0ea082bd98b1cbca79c
