### ISSUE TITLE
雪合戦中のメイドの動きの問題

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#4]
契約したメイドがフリーモードに入った後、雪合戦のアクションは常に座っているか歩くかを切り替えます。この問題はfp.008に現れ始めました。
Google翻訳を使用していますが、意味が異なる場合があります。ごめんなさい

**Comment by firis-games** [comment]
雪合戦モードとエスコートモードのAI切り替えが内部的に頻繁に発生していたため、自由行動のお座りアニメーションの挙動がおかしくなって現象が発生している。
エスコートモードを一定時間以上維持しないとお座りアニメーションが発生しないように処理を修正します。対応版はver.fp.012でリリース予定です。

commit: feaedf9458dc537fe12ad8f895989fa0596e0d5f
