### ISSUE TITLE
リトルメイドの自爆モードの問題

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#40]
LMR 1.10.2のリトルメイドは、TNTを装備した後に爆発モードに入り、リトルメイドはモンスターを攻撃し、ダメージを受けた後に爆発します。 LMRFPでは、自己爆発モードのリトルメイドがモンスターを攻撃する能力を失います。これはバグですか？

**Comment by firis-games** [comment]
自爆モードは今後、機能自体を削除または新機能への置き換えを予定しています。
連絡されている内容については変更予定はありませんので仕様となります。
