### ISSUE TITLE
「MakedSpawnEgg」を使用して生成されたLittlemaidのバグ

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#41]
「Maked Spawn Egg＃5206」を使用して生成されたリトルメイドの視点は非常に高くなりますが、「Spawn Littlemaid＃383」を使用して生成されたリトルメイドにはこの問題はありません。 このバグは修正できますか？

左：Maked Spawn Egg、右：Spawn Littlemaid
![2020-05-20_09 02 50](https://user-images.githubusercontent.com/58005561/82391329-02187180-9a7c-11ea-9de7-0b07b7716b00.png)

**Comment by firis-games** [comment]
初回スポーン時のモデルのリフレッシュ処理を追加しました。

対応版はver.fp.040でリリース予定です。

commit: 2c5d9010007d1868767a3cb33ceb246d97da3fc8
