### ISSUE TITLE
他のプレイヤーはメイドを見ることができず、影を見るだけです。

### ISSUE THREAD

**Issue by ColaLiao** [firis-games/LittleMaidReengagedFirisPatch#49]
When used in single player game, and open to LAN.
other players can not see maids, only see shadow.
and if they right click the shadow to open maid's UI,
their game will crash.

シングルプレイヤーゲームで使用する場合、LANにオープンします。
他のプレイヤーはメイドを見ることができず、影を見るだけです。
影を右クリックしてメイドのUIを開くと、
彼らのゲームはクラッシュします。

**Comment by firis-games** [comment]
現象が発生した詳しい情報を記載して下さい。
・利用しているMODのバージョン（LMRFP/LMLibrary）
・クラッシュ時のクラッシュログ

**Comment by ColaLiao** [comment]
私は問題の原因を見つけました、
LittleMaidResourceフォルダーが自動的に生成されなかった理由がわかりません。

**Comment by ColaLiao** [comment]
他にもいくつか問題があります
自然スポーンのメイドは時々クラッシュするか、ゲームから切断されます、
メイドの周りの変化はゲームをクラッシュまたは切断させます、
たとえば、土壌は耕作地になります。

**Comment by ColaLiao** [comment]
問題が発生したときのクラッシュレポートはありません

**Comment by firis-games** [comment]
LMLibrary-1.0.4ではLittleMaidResourceが生成されない場合があります。
LMLibrary-1.0.5以上にアップデートして下さい。
問題を報告する場合は詳細を記載して下さい。
クラッシュレポートがない場合はサポートできません。
