### ISSUE TITLE
Is it possible to make all the features of the old version of littlemaidmob in FirisPatch?

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#5]
Features like littlemaids can wear monster skull and flowers on head.or the effects of arrows pierced on the littlemaid.and players can let littlemaid ride on their shoulders
Is it possible?

**Comment by firis-games** [comment]
LittleMaidReengaged Firis's PatchはMMMさんのLittleMaidMob1.6.2ではなくVercleneさんのLittleMaidReengaged1.10.2をベースに作成しています。
LittleMaidMob1.6.2は既に動作する環境が存在していないため動作の確認ができません。
Minecraft本体のバージョンアップにより再現が難しいものが存在しています。
LittleMaidReengaged1.10.2に存在しない機能は新規で作成する必要があります。
このため全てのLittleMaidMob1.6.2を追加することは難しいです。
