### ISSUE TITLE
メイドがアイテムを手に取り、メイドインターフェースを開くと、ゲームが切断またはクラッシュします。

### ISSUE THREAD

**Issue by ColaLiao** [firis-games/LittleMaidReengagedFirisPatch#50]
メイドがアイテムを手に取り、メイドインターフェースを開くと、ゲームが切断またはクラッシュします。

Forge 14.23.5.2847
LittleMaidReengaged_FirisPatch-9.2.1.fp.045
LMLibrary-1.0.4
Pixelmon-1.12.2-8.0.2-universal

**Comment by ColaLiao** [comment]
サトウキビを植えるメイドにも同じ問題があります

**Comment by ColaLiao** [comment]
問題が発生したときのクラッシュレポートはありません

**Comment by ColaLiao** [comment]
この問題をポケモンモジュールにも報告しました

**Comment by firis-games** [comment]
問題を報告する場合は詳細を記載して下さい。
クラッシュレポートがない場合はサポートできません。
