### ISSUE TITLE
本をメイドさんに使用するとサーバーがエラーを起こす

### ISSUE THREAD

**Issue by HIRO0132** [firis-games/LittleMaidReengagedFirisPatch#51]
forge-1.12.2-14.23.5.2854 サーバー環境下で、

LittleMaidReengaged_FirisPatch-9.2.1.fp.045

LMLibrary-1.0.5

のみを入れ、サーバーに入りメイドさんの敵対モブ設定画面を開くとするとサーバーがエラーを起こし、サーバーから強制的に退出させられます。
サーバー自体は落ちず、再度入ると問題なくプレイできますが、ふたたび設定画面を開くとまた強制的に退出させられます。
同構成のシングルプレイでは発生しません。
もしよろしければ対応お願いします。
ログ
https://pastebin.com/KnAdzywU
13:29:15からがエラー内容です

**Comment by firis-games** [comment]
マルチ環境でIFFを設定しようとするとクラッシュする問題に対応しました。
対応版はver.fp.046でリリース予定です。

commit: 95dec68120c297f1e2d331272048d9fda6c307ec
