### ISSUE TITLE
「Maid Contract」で作成したメイドさんの視点に問題があります。

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#53]
「Maid Contract」で生成されたchloe2やbeverly7などのメイド、生成後のメイドの視点が高すぎる
使用したスキンパッケージ：LittleMaidAppendPack-1.0.2.jar
![2020-08-17_02 13 04](https://user-images.githubusercontent.com/58005561/90340465-60c99900-e033-11ea-9357-d52ae5633a63.png)
![2020-08-17_02 14 03](https://user-images.githubusercontent.com/58005561/90340470-6626e380-e033-11ea-9ca2-1ae3427c88da.png)

**Comment by firis-games** [comment]
メイドさんの契約書からスポーンしたメイドさんに対して通常スポーンエッグと同様にマルチモデルのサイズを変更するように対応しました。
commit : 7dae5defeb327a39d2b34d7f5e91ad3e62123e0b

次バージョンにて対応予定です。
