### ISSUE TITLE
メイドさんが落とした「メイドお土産」は発光効果がありません。

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#54]
メイドの死後にドロップされた「メイドお土産」はグロー効果がなく、プレイヤーが投げた後にのみグロー効果を持ちます。
![2020-08-17_02 19 58](https://user-images.githubusercontent.com/58005561/90340625-899e5e00-e034-11ea-8e2c-ce0c3ebed5af.png)
![2020-08-17_02 20 04](https://user-images.githubusercontent.com/58005561/90340631-a0dd4b80-e034-11ea-9f39-badd3d69a0fb.png)

**Comment by firis-games** [comment]
メイドさんから直接ドロップしたメイドの土産も発光エフェクトが反映されるように対応しました。
commit : aa707533d4ce95abc72b92952e1cf38a1c61b840

次バージョンにて対応予定です。
