### ISSUE TITLE
雪玉を拾うときのメイドの動きの問題

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#57]
新バージョンでは、メイドさんは雪玉を拾うアクションがありません。深刻なバグではありませんが、修正できますか？

fp.048：
![20200818-05333854_20200818062645](https://user-images.githubusercontent.com/58005561/90446797-fbea6d80-e11c-11ea-8860-ad14b181fca8.gif)

fp.033：
![20200818-054405714_20200818062820](https://user-images.githubusercontent.com/58005561/90446941-3522dd80-e11d-11ea-880c-d033e31483fe.gif)

**Comment by firis-games** [comment]
雪玉を拾う際にスニークするように変更しました。

次回バージョンにて対応予定です。

commit : c0361dbac901afbbff71a920f2fa0b3739553f2b
