### ISSUE TITLE
Problems with littlemaids in multiplayer

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#6]
contracted littlemaids only follow host player command

**Comment by firis-games** [comment]
契約したご主人様以外にリトルメイドが反応しないということでしょうか。
その場合は仕様通りの動きとなります。
違う場合は、詳しい情報を記載下さい。

**Comment by erer00gg** [comment]
LAN接続では、他のプレイヤーの契約のメイドは彼らの命令に従わなかった。 他のプレイヤーはメイドのインベントリを開くことも、メイドにフォローさせることもできません。

**Comment by firis-games** [comment]
契約したメイドさんはご主人様以外の命令には従いません。インベントリを開けないことも、メイドさんのフォローができないことも仕様通り問題ない動きです。

**Comment by erer00gg** [comment]
1.10.2lmrの設定ファイルにはcheckOwnerName = trueがありますが、これはfirispatchの設定ファイルにはありません。 これは、マルチメイドモードで1人だけを認識するリトルメイドと関係があると思います
