### ISSUE TITLE
野良メイドの透明化現象

### ISSUE THREAD

**Issue by matsubalite** [firis-games/LittleMaidReengagedFirisPatch#60]
fp.048でテクスチャパックなどを導入して、野良メイドをスポーンさせた後、出現している野良メイドのテクスチャを削除した所、野良メイドが透明化しました。該当テクスチャを入れ直したら、透明化した野良メイドは再び視認できるようになりました。

↓一連の現象
https://twitter.com/matsubacraft/status/1296077153218387969

**Comment by firis-games** [comment]
マルチモデル単位ではなくテクスチャ単位で外した場合もデフォルトモデルを適応する機能を追加しました。
該当のマルチモデルまたはテクスチャが存在しない場合はマルチモデルをdefault_Orignに変更します。
変更後にテクスチャを戻した場合もdefault_Orignのままになります。

追加機能は次回更新時に公開予定です。

commit : 8f3dda6c1c2b67010cb0fb5fbe297606a99cb216
