### ISSUE TITLE
木こりメイドが木の上にいておりてこない

### ISSUE THREAD

**Issue by nukesuke** [firis-games/LittleMaidReengagedFirisPatch#61]
木こりメイドが木の上にのって降りてこずに植林場が止まることがありました
頻繁に起こるので再現性はあると思います
木こりメイドはダメージ受けてでも優先的に段差を降りる処理をいれれば緩和すると思います
あとできれば葉ブロックに埋まった時はその葉ブロックを壊す処理が欲しいです
あわや窒息死ということがありましたので
以下、問題のスクリーンショット
![2020-08-20_10 43 18](https://user-images.githubusercontent.com/69803850/90707275-33e6e180-e2d2-11ea-9d16-67642fbac59f.png)

**Comment by firis-games** [comment]
木こりメイドさんの木登り・葉埋まり対策に伐採条件を追加します。
・メイドさんの足元が葉ブロックまたは原木ブロックの場合伐採を行う。
・メイドさんの座標に葉ブロックまたは原木ブロックが存在する場合に伐採を行う。
落下によるダメージ、木以外の対象に反応する可能性が高まる場合もありますが木登り状態や葉埋まり状態からは自力で回避できるようになります。

追加機能は次回更新時に公開予定です。

commit : fe8b1d84373949643896079de1bd02ad074997cd
