### ISSUE TITLE
メイドが「Rats」の敵対的な生き物に近接攻撃で殺された後、ゲームがクラッシュする

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#62]
RatsModのPlagueBeastのような敵対的なクリーチャーによってメイドが殺された後、ゲームがクラッシュします。
使用されるMOD：
rats-3.2.14-1.12.2
LittleMaidReengaged_FirisPatch-9.2.4.fp.048      
[crash-2020-08-20_14.36.28-server.txt](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/5100916/crash-2020-08-20_14.36.28-server.txt)

**Comment by firis-games** [comment]
rats-3.2.14-1.12.2の処理でクラッシュしています。
該当Mod側へ連絡して下さい。
