### ISSUE TITLE
HiFMスキンパックと「うつ伏せ」などのアクションの互換性について。

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#63]
メイドがHiFMスキンパックの「HiFM_MAlrun」および「HiFM_THom」スキンを使用している場合、座っているときに「うつ伏せ」などのアクションに切り替えると問題が発生します。このバグを修正できますか？ または、メイドのアクションを更新するなど、新しい機能を追加できますか？

![20200907-061952788_20200907064924](https://user-images.githubusercontent.com/58005561/92335935-a9c2b980-f0d6-11ea-8e8f-c3ed49fce0e6.gif)
![20200907-062045502_20200907065113](https://user-images.githubusercontent.com/58005561/92335958-d8d92b00-f0d6-11ea-813e-0f57af361535.gif)

**Comment by firis-games** [comment]
該当のマルチモデルとモーション処理の相性が悪いため発生しています。
モーション処理は後付のものになるためすべてのマルチモデルには対応できません。
該当のマルチモデルでモーション機能を使わない等で対応して下さい。

モーションの追加についてはLMLibraryを前提MODとしてfiris.lmmm.api.model.motion.ILMMotionの実装を作成しLMLibraryAPI.registerLittleMaidMotionで登録することで可能です。
firis.lmlib.api.motionにLMLibraryで追加しているモーションが存在しますので参考にして下さい。
