### ISSUE TITLE
メイドに関するいくつかのマイナーなバグといくつかの提案。

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#65]
リトルメイドがヘルメットを装備している場合、リトルメイドはプレーヤーに頭を傾けません。
![2020-10-21_15 46 42](https://user-images.githubusercontent.com/58005561/96687727-41484700-13bb-11eb-9e6a-39f831aeee0b.png)
![2020-10-21_15 47 11](https://user-images.githubusercontent.com/58005561/96687749-47d6be80-13bb-11eb-96f4-aca4d05932b6.png)

**Comment by erer00gg** [comment]
littleForcesスキンパックのいくつかのバグについては、少し遅れる可能性がありますが、littleForcesスキンパックには、fp.029バージョンより前のUIインターフェイスで特別な表現があり、fp.029以降は無効になります。

fp.053
![2020-10-21_15 50 12](https://user-images.githubusercontent.com/58005561/96688582-4d80d400-13bc-11eb-82a3-9790ad2d16e0.png)

fp.020
![2020-10-21_16 27 05](https://user-images.githubusercontent.com/58005561/96688635-5c678680-13bc-11eb-8e33-3c52185754a1.png)

**Comment by erer00gg** [comment]
littlemaidmobの1.6.2-1.7.10バージョンでは、メイドに砂糖を使用すると、モードを切り替えながらメイドを癒すこともできます（1砂糖で1HPが回復します）。 この古い機能がFirisPatchで再現できることを願っています！
![2020-10-21_15 47 34](https://user-images.githubusercontent.com/58005561/96690149-48bd1f80-13be-11eb-9734-21e42731b92e.png)

**Comment by firis-games** [comment]
１．元からの動きなので変更予定はありません。
２．クライアント側のインベントリフラグが反応していないので対応します。
３．砂糖を与えた時のヒール機能は対応します。

次回バージョンにて対応予定です。
