### ISSUE TITLE
「achievement.myfavorite」が正しく表示されません。

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#67]
「Achievement.myfavorite」はすべての言語で正しく表示されるわけではありません。
![2020-10-22_14 11 45](https://user-images.githubusercontent.com/58005561/96828127-03f2c080-1472-11eb-8a75-fd15325c528d.png)
![2020-10-22_14 12 20](https://user-images.githubusercontent.com/58005561/96828133-05bc8400-1472-11eb-9df0-1bf1cc191a76.png)

**Comment by firis-games** [comment]
進捗表示用のメッセージIDを変更しました。。

次回バージョンにて対応予定です。

commit : be13e42c72fbd0a9ea86467956d83f5421757e85
