### ISSUE TITLE
リトルメイドのモーションに関する提案

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#68]
リトルメイドの待機モーションは、特定のスキンパック（HiFMなど）をサポートしていないため、奇妙なモーションが発生します、そして、リトルメイドの間違ったモーションを元に戻すことはできません。 
リトルメイドの待機モーションをオンまたはオフに設定できますか？ たとえば、設定ファイルにリトルメイドモーションに関連する設定を追加して、プレーヤーがそれをオンにするかオフにするかを選択できるようにしますか？

**Comment by firis-games** [comment]
リトルメイドの追加モーションは能動的に設定しない限り動作しません。
そのため別途設定を追加する必要性を感じません。
