### ISSUE TITLE
LagGoggles導入時にモデルを変更しようとするとクラッシュする

### ISSUE THREAD

**Issue by natainakata** [firis-games/LittleMaidReengagedFirisPatch#69]
こんにちわ、お世話になっております。
大量のMOD（200個近く）を導入した環境において、メイドさんのモデルを変更しようとするとクラッシュする事例を確認しました。
どうやら、LagGooglesというMODと競合しているようです。
お手数をおかけしますが、クラッシュレポートを送りますのでご確認をお願いします。
[crash-2020-11-21_11.21.24-client.txt](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/5576888/crash-2020-11-21_11.21.24-client.txt)

**Comment by firis-games** [comment]
1点確認ですが導入しているマルチモデルの中にlittleMaidMob-NM_peko190は含まれていますか。
その場合最新版ではこのモデルは対応できていないのでクラッシュする可能性があります。
NMに含まれるマルチモデルを利用したい場合はLittleMaidAppendPackにNMが含まれているのでそちらで確認してみてください。

**Comment by natainakata** [comment]
確認したところNMが導入されていたので外したら解消しました、お手数をおかけしました。
