### ISSUE TITLE
メイドは音を出しません。

### ISSUE THREAD

**Issue by mageofsleep** [firis-games/LittleMaidReengagedFirisPatch#7]
このバージョンのlittleMaidMobを発見したばかりで、本当に良いと言わざるを得ません。 私が遭遇している唯一の問題は、メイドが音を出さないことです。
SoundPackはminecraft \ mods \ LittleMaidReengagedにあり、littlemaidmob.cfgとsounds.jsonが含まれています。 littleMaidMobフォルダーにはサウンドファイルがあります。 これは正しいですか？
別の場所に配置する必要がありますか、これはグリッチですか？
機械翻訳を使用しています。

**Comment by firis-games** [comment]
例えばlittleMaid_WOLF_v103.zipというボイスパックを導入する場合は以下の通りの場所に配置します。
minecraft/mods/littleMaid_WOLF_v103.zip

zipファイルを解凍せずにそのままmodフォルダの下に置くとボイスパックが反映されます。
ボイスパックの中に日本語ファイル名が含まれると正常に動作しません。

**Comment by mageofsleep** [comment]
おおおおおおお、ありがとうございます!
