### ISSUE TITLE
メイドさんになる本について

### ISSUE THREAD

**Issue by rikubon** [firis-games/LittleMaidReengagedFirisPatch#70]
メイドさんになる本を知らずに使用してしまい、スキンがメイドさんになってしまいました。普通のスキンが使用したいのですがどのようにすれば治せるでしょうか？教えてください。

**Comment by firis-games** [comment]
LMアバター導入時にスティーブモデルとリトルメイドモデルの切り替え方法を質問していると受け取ります。
デフォルトでは「:」キーでスティーブモデルとリトルメイドモデルを切り替えることができます。
