### ISSUE TITLE
MysticalWorld 1.9.2 導入時にメイドがアンデッド系からダメージを受けるとクラッシュする

### ISSUE THREAD

**Issue by hexqua** [firis-games/LittleMaidReengagedFirisPatch#71]
HuskやZombie Pigman等のアンデッド系からダメージを受けるとNullPointerExceptionでクラッシュします。
他MODとの競合且つメイドさん側に非がなさそうなクラッシュで恐縮ですが対応可能でしたら対応をお願いします。
(MysticalWorldで追加される銀防具によるBLESSED属性の取得回りでどこかでNullになってしまうようです)

使用Minecraftバージョン : 1.12.2
使用Forgeバージョン : 14.23.5.2854
使用MOD : 
LittleMaidReengaged_FirisPatch-9.3.6.fp.056
LMLibrary-1.1.5
mysticallib-1.12.2-1.9.0
mysticalworld-1.12.2-1.9.2
Patchouli-1.0-20

再現手順:
1. ワールドを生成する。(検証時はSuperFlat、Creativeで作成)
2. 契約書で契約済みメイドさんを生成し、木の剣等の近接武器を持たせてFencerモードにする。(防具は未着用)
3. Zombie Pigmanのスポーンエッグを使いZombie Pigmanを出現させる。
4. Zombie Pigmanの反撃でメイドさんがダメージを受けた瞬間にクラッシュ。
(Spider等の非アンデッドであれば反撃を受けてもクラッシュしません)

MysticalWorld側での該当クラス
https://github.com/MysticMods/MysticalWorld/blob/master/src/main/java/epicsquid/mysticalworld/events/DamageHandler.java

クラッシュ時ログ
[latest.log](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/5827345/latest.log)

**Comment by firis-games** [comment]
ログと処理を確認しましたがMysticalWorldで使用されているBLESSEDという特殊効果が原因でクラッシュしているようです。
（アンデットから攻撃を受けた際に火ダメージを自動で反撃する効果）

リトルメイドは通常のEntityと違いPlayerを偽装しているためMysticalWorld側でPlayerとして判断され上記の特殊処理が動作します。
その際にリトルメイドはMysticalWorldがPlayerに独自に追加しているBLESSEDの属性を持っていないためエラーとなりクラッシュします。

この問題はリトルメイド側で対応するためには仕様を大きく変える必要があり対応できません。どうしても対応が必要な場合はMysticalWorld側であれば対応は容易（PlayerにBLESSEDがないパターンを追加するだけ）なのでそちらへお知らせください。
