### ISSUE TITLE
Imlibrary 1.1.5

### ISSUE THREAD

**Issue by got991** [firis-games/LittleMaidReengagedFirisPatch#72]
必要なモジュール( lmlibrary 1.1.5以降)が見つからない。

**Comment by got991** [comment]
返事するなら英語を使ったほうがいいです。

**Comment by erer00gg** [comment]
here:
[https://github.com/firis-games/LittleMaidReengagedFirisPatch/releases/tag/ver.fp.055](url)

**Comment by firis-games** [comment]
erer00gg氏記載の通りver.fp.055より入手可能です。
また入手先についてはver.fp.056のリリース説明にも同様のことを記載しています。
