### ISSUE TITLE
LittleMaidAvaterのバグ？

### ISSUE THREAD

**Issue by SCh11** [firis-games/LittleMaidReengagedFirisPatch#73]
Version:
LittleMaidAvater-1.2.2(configで LittleMaidAvatarDev.AdjustSize=true に設定しています)
LMLibrary-1.1.5
1.12.2-forge-14.23.5.2854

ハサミで葉を回収しようとしたり、効率強化Ⅴのついたシャベルなどで土を掘ると、破壊のパーティクルは出るものの、
ドロップもせず、破壊されていないのか通ることもできません。いずれもリログすると治ります。
これはバグですか？それとも設定の問題ですか？

![movie3(2)](https://user-images.githubusercontent.com/29685603/112708910-6d32a000-8ef8-11eb-8312-d72fca81feb0.gif)
![movie2](https://user-images.githubusercontent.com/29685603/112709028-3f019000-8ef9-11eb-9461-0d0d8d5ffa79.gif)

**Comment by firis-games** [comment]
LittleMaidAvatarDev.AdjustSizeを含む設定値がLittleMaidAvatarDevから始まるものは正規の機能ではなく仮機能（完全には動いていないもの）になります。

現状サイズの変更は可能となっていますが事象の通りブロックの破壊を伴うと動きがおかしくなる場合があります。
そのため通常サバイバルで利用する場合はLittleMaidAvatarDev系の設定はうまく動かない可能性があることを考慮してから使用してください。
