### ISSUE TITLE
リトルメイドとエンチャントの瓶によって引き起こされたバグ

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#74]
このバグは、バージョンfp.047以降に発生しています。 リトルメイドからエンチャントの瓶を入手するときにマウスの右クリックの頻度が速すぎると、リトルメイドの経験値がなくなると、プレーヤーの装備が混乱して消えてしまいます。 （ただし、ゲームに再度参加すると、プレーヤーの装備が復元されます）

https://user-images.githubusercontent.com/58005561/113514603-9911ed80-95aa-11eb-8515-d95f757142a5.mp4

**Comment by firis-games** [comment]
ラグによる表示の問題についてはリログすれば解消することなので一旦は様子見します。
今後同じような問題が多数発生した場合は対応を検討します。
