### ISSUE TITLE
「LMRFP」と「torohealth」のバグ

### ISSUE THREAD

**Issue by erer00gg** [firis-games/LittleMaidReengagedFirisPatch#76]
「torohealth-damage-indicators」をインストールした後、リトルメイドが鎧を着ると、インベントリが表示されると黒い画面が表示されます。

https://user-images.githubusercontent.com/58005561/114258997-bb21ca80-9a05-11eb-9339-1d1d782a64b9.mp4

**Comment by firis-games** [comment]
他のMODの影響による描画の挙動については致命的なものでない限りは対応しません。
今回の件についてもプレイに支障はないので対応しません。
