### ISSUE TITLE
メイドさんの動作で困っていることがあります

### ISSUE THREAD

**Issue by jagabata** [firis-games/LittleMaidReengagedFirisPatch#8]
こんにちは。LMRを精力的に開発してるひとがいてうれしいです。
昨日フィリスさんのMODを見つけ先ほど早速導入させていただきました。

以前からメイドさんの動作で困っていたことがあり（本家LMRのころからある動作です）、改善していただけるなら改善していただきたい事があります。

その困っていることと言うのは、毛刈りや農家モードのメイドさんのときのことです。例えば近くに羊がいるときに、毛を刈ってもらいたい羊を柵の中に入れているのですがその中にメイドさんも一緒に中にいるとき、柵の範囲外の近い場所に羊がいる場合、その届かない羊の毛を刈ろうと自分の柵の中の羊の毛が復活しようが柵の外の羊の毛を刈ろうとしているのか自分の柵の中の羊を刈らずにいる状態になってしまうことです。
作物でも同じことがおき、届かない作物が近くにあってメイドさんが認識している場合、そこでメイドさんの動作が止まってしまいます。

これでなにが困るのかというと、例えばメイドさんに仕事をしてもらいたい羊刈りの牧場や畑を隣接させて設置することができずに、メイドさんが作物などを認識しない十分な距離をとって畑や牧場を設置しなくてはならないのです。

この現象どうにかならないでしょうか。毛が刈れない状態や作物が収穫できないときはあきらめて、近くのものを優先させることとかできないでしょうか。

よろしくおねがいします。

追伸：
今回のこの件とは別のことで、農家モードのメイドさんがチェストが近くにあってチェストに余裕があるのにメイドさんのインベントリがいっぱいにも関わらず、チェストに入れない現象があります。
収穫はしているようですがアイテム化した状態の作物が放置されていました。
メイドさんのインベントリの中の作物がすべてのスロットが64個でもう拾えない状態でした。
どうやらチェストに収納するときとしないときがあるみたいです。
バージョンはLittleMaidReengaged_FirisPatch-8.1.6.141.fp.016、forge1.12.2-14.23.5.2847です。

**Comment by firis-games** [comment]
毛刈りメイドさん、農家メイドさん、サトウキビ農家メイドさんで届かない対象オブジェクトがある場合に一定時間後にターゲットを疑似的にリセットする処理を追加しました。
ある程度時間をおいてからリセットされるためすぐにターゲットが変わるわけではありません。
また追伸についてはこちらで現象の再現ができなかったため対応していません。
対応版はver.fp.018でリリース予定です。
commit:
9882790a56bde0287866b9e26419360518e16293
6fef9c4cf630b0ba149efaa1ab1948e1353cf8ec
913799a118fe74659e5fbe818107dce3beab52ff
