### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Uziel25** [firis-games/LittleMaidReengagedFirisPatch#80]
The below crash only happens when the Littlemaids mod is installed.  It appears to occur when they are engaged in  combat.  The first time it happened it was fighting a zombie that spawned with buffs from the "Champions" mob.  I uninstalled the mod and logged back in and the error was gone.  I reinstalled the mod afterwards.  When exploring underground it crashed again, and I uninstalled the mod a 2nd time.  When I logged back in again the error was gone.  I love the mod but spending he resources to make the maids stronger only to have the game freeze when they get in combat is a bit much.  To be clear, it does not crash every time they go into combat.  

Please let me know if there is anything that I can do to allow the mod to run in my game.  I love the mod; you've done a great job with it.  I will definitely miss having the maids in my hunting party.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.042210-core.jar)
  McLib core mod (mclib-2.3.5-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OTGCorePlugin (OTG-Core.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 9/14/21 2:59 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at epicsquid.mysticalworld.events.DamageHandler.onLivingDamage(DamageHandler.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_269_DamageHandler_onLivingDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:610)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP.W_damageEntity(EntityLittleMaidAvatarMP.java:628)
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.func_70665_d(EntityLittleMaid.java:2157)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.func_70097_a(EntityLittleMaid.java:2258)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:369)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at epicsquid.mysticalworld.events.DamageHandler.onLivingDamage(DamageHandler.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_269_DamageHandler_onLivingDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:610)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaidAvatarMP.W_damageEntity(EntityLittleMaidAvatarMP.java:628)
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.func_70665_d(EntityLittleMaid.java:2157)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at net.blacklab.lmr.entity.littlemaid.EntityLittleMaid.func_70097_a(EntityLittleMaid.java:2258)
	at net.minecraft.entity.projectile.EntityArrow.func_184549_a(EntityArrow.java:369)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:267)
	at net.minecraft.entity.projectile.EntityTippedArrow.func_70071_h_(SourceFile:98)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.entity.projectile.EntityTippedArrow)
	Entity ID: 13639
	Entity Name: Arrow
	Entity's Exact location: 358.59, 12.88, 161.72
	Entity's Block location: World: (358,12,161), Chunk: (at 6,0,1 in 22,10; contains blocks 352,0,160 to 367,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.83, -0.45, -1.42
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Earth
	All players: 1 total; [EntityPlayerMP['Uziel25P'/12841, l='Earth', x=359.26, y=22.00, z=148.61]]
	Chunk stats: ServerChunkCache: 395 Drop: 0
	Level seed: 66725930
	Level generator: ID 07 - RTG, ver 0. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (259,64,234), Chunk: (at 3,4,10 in 16,14; contains blocks 256,0,224 to 271,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 458168 game time, 465932 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10405 (now: false), thunder time: 76774 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1413666632 bytes (1348 MB) / 7056916480 bytes (6730 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 1, tcache: 1, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 147 mods loaded, 146 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                  | Source                                           | Signature                                |
	|:------ |:----------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                     | 9.42                     | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit               | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| LCHIJA | otgcore                 | 1.12.2-v9.3              | minecraft.jar                                    | None                                     |
	| LCHIJA | movillages              | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| LCHIJA | fastbench               | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                   | None                                     |
	| LCHIJA | actuallyadditions       | 1.12.2-r152              | ActuallyAdditions-1.12.2-r152.jar                | None                                     |
	| LCHIJA | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | actuallybaubles         | 1.1                      | ActuallyBaubles-1.12-1.1.jar                     | None                                     |
	| LCHIJA | additionalcompression   | 3.4                      | Additional-Compression-1.12.2-3.4.jar            | None                                     |
	| LCHIJA | advanced-fishing        | 1.3.3                    | Advanced-Fishing-1.12.2-1.3.3.jar                | None                                     |
	| LCHIJA | al                      | 1.3                      | al_1.12-1.3.jar                                  | None                                     |
	| LCHIJA | crafttweaker            | 4.1.20                   | CraftTweaker2-1.12-4.1.20.660.jar                | None                                     |
	| LCHIJA | jei                     | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                        | None                                     |
	| LCHIJA | appleskin               | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LCHIJA | mantle                  | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHIJA | thedragonlib            | 1.12.2-5.3.0             | thedragonlib-1.12.2-5.3.0.jar                    | None                                     |
	| LCHIJA | armorplus               | 1.12.2-11.28.0.69        | armorplus-1.12.2-11.28.0.69.jar                  | None                                     |
	| LCHIJA | quark                   | r1.6-179                 | Quark-r1.6-179.jar                               | None                                     |
	| LCHIJA | autoreglib              | 1.3-32                   | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCHIJA | bettercaves             | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                     | None                                     |
	| LCHIJA | bettermineshafts        | 1.12.2-2.2.1             | BetterMineshaftsForge-1.12.2-2.2.1.jar           | None                                     |
	| LCHIJA | betternether            | 0.1.8.6                  | betternether-0.1.8.6.jar                         | None                                     |
	| LCHIJA | betterquesting          | 3.5.329                  | BetterQuesting-3.5.329.jar                       | None                                     |
	| LCHIJA | blocklings              | 1.0                      | Blocklings+6.0.1_b+-+1.12.2.jar                  | None                                     |
	| LCHIJA | bloodmoon               | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | customspawner           | 3.11.4                   | CustomMobSpawner-3.11.5.jar                      | None                                     |
	| LCHIJA | bmcmsfix                | 1.0.0                    | BloodmoonCMSFix-1.12.2-1.0.0.jar                 | None                                     |
	| LCHIJA | bookshelf               | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bountifulbaubles        | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.6.jar               | None                                     |
	| LCHIJA | forgelin                | 1.8.4                    | Forgelin-1.8.4.jar                               | None                                     |
	| LCHIJA | bountiful               | 2.2.2                    | Bountiful-2.2.2.jar                              | None                                     |
	| LCHIJA | buildcraftlib           | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcraftcore          | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcraftbuilders      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcrafttransport     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcraftsilicon       | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcraftenergy        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | natura                  | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                       | None                                     |
	| LCHIJA | forestry                | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                    | None                                     |
	| LCHIJA | buildcraftcompat        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcraftfactory       | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | buildcraftrobotics      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                     | None                                     |
	| LCHIJA | castle_dungeons         | 1.3                      | castle_dungeons-2.2p1-1.12.2-forge.jar           | None                                     |
	| LCHIJA | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCHIJA | champions               | 1.12.2-1.0.11.10         | champions-1.12.2-1.0.11.10.jar                   | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | charm                   | 1.4                      | Charm-1.12.2-1.4.1.jar                           | None                                     |
	| LCHIJA | clienttweaks            | 3.1.11                   | ClientTweaks_1.12.2-3.1.11.jar                   | None                                     |
	| LCHIJA | cyclopscore             | 1.6.7                    | CyclopsCore-1.12.2-1.6.7.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | commoncapabilities      | 2.4.8                    | CommonCapabilities-1.12.2-2.4.8.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | controlling             | 3.0.10                   | Controlling-3.0.10.jar                           | None                                     |
	| LCHIJA | craftingtweaks          | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                  | None                                     |
	| LCHIJA | ctgui                   | 1.0.0                    | CraftTweaker2-1.12-4.1.20.660.jar                | None                                     |
	| LCHIJA | crafttweakerjei         | 2.0.3                    | CraftTweaker2-1.12-4.1.20.660.jar                | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCHIJA | cucumber                | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                        | None                                     |
	| LCHIJA | cyclicmagic             | 1.20.11                  | Cyclic-1.12.2-1.20.11.jar                        | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHIJA | dailies                 | 1.12.2-6                 | dailies-1.12.2-6.jar                             | None                                     |
	| LCHIJA | waila                   | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | darkutils               | 1.8.230                  | DarkUtils-1.12.2-1.8.230.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | defiledlands            | 1.4.3                    | defiledlands-1.12.2-1.4.3.jar                    | None                                     |
	| LCHIJA | disenchanter            | 1.7                      | disenchanter-[1.12]1.7.jar                       | None                                     |
	| LCHIJA | mocreatures             | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar              | None                                     |
	| LCHIJA | enchdesc                | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | golems                  | 7.1.9                    | ExtraGolems-1.12-7.1.9.jar                       | None                                     |
	| LCHIJA | extrautils2             | 1.0                      | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LCHIJA | fastfurnace             | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                     | None                                     |
	| LCHIJA | fastleafdecay           | v14                      | FastLeafDecay-v14.jar                            | None                                     |
	| LCHIJA | gravestone              | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar               | None                                     |
	| LCHIJA | gravestone-extended     | 1.3.5.1                  | GraveStone-1.12.2-Extended-1.3.5.1.jar           | None                                     |
	| LCHIJA | grimoireofgaia          | 1.7.2                    | GrimoireOfGaia3-1.12.2-1.7.2.jar                 | None                                     |
	| LCHIJA | guardscraft             | 1.0.5                    | guardscraft-1.12.2-1.0.5.jar                     | None                                     |
	| LCHIJA | heroicarmory            | 1.1.3                    | heroicarmory-1.2.0.jar                           | None                                     |
	| LCHIJA | infernalmobs            | 1.7.6                    | InfernalMobs-1.12.2.jar                          | None                                     |
	| LCHIJA | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks           | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCHIJA | jeiintegration          | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar                  | None                                     |
	| LCHIJA | jeivillagers            | 1.0                      | jeivillagers-1.12-1.0.2.jar                      | None                                     |
	| LCHIJA | journeymap              | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                      | None                                     |
	| LCHIJA | harvestcraft            | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                  | None                                     |
	| LCHIJA | jehc                    | 1.7.2                    | just-enough-harvestcraft-1.12.2-1.7.2.jar        | None                                     |
	| LCHIJA | jeresources             | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCHIJA | kagic                   | X11p13                   | kagic-X11p13.jar                                 | None                                     |
	| LCHIJA | libraryex               | 1.2.2                    | LibraryEx-1.12.2-1.2.2.jar                       | None                                     |
	| LCHIJA | lmlibrary               | 1.1.5                    | LMLibrary-1.1.5.jar                              | None                                     |
	| LCHIJA | lmavatar                | 1.2.2                    | LittleMaidAvatar-1.2.2.jar                       | None                                     |
	| LCHIJA | lmreengaged             | 9.3.8.fp.058             | LittleMaidReengaged_FirisPatch-9.3.8.fp.058.jar  | None                                     |
	| LCHIJA | llor                    | 1.1.6-mc1.12.2           | LLOverlayReloaded-1.1.6-mc1.12.2.jar             | None                                     |
	| LCHIJA | lootbags                | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                      | None                                     |
	| LCHIJA | mclib                   | 2.3.5                    | mclib-2.3.5-1.12.2.jar                           | None                                     |
	| LCHIJA | metamorph               | 1.2.10                   | metamorph-1.2.10-1.12.2.jar                      | None                                     |
	| LCHIJA | mob_grinding_utils      | 0.3.13                   | MobGrindingUtils-0.3.13.jar                      | None                                     |
	| LCHIJA | moremobss               | 1.0.0                    | More Mobs 1.12.2.jar                             | None                                     |
	| LCHIJA | mousetweaks             | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCHIJA | mysticalworld           | 1.12.2-1.10.0            | mysticalworld-1.12.2-1.10.0.jar                  | None                                     |
	| LCHIJA | naturescompass          | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                  | None                                     |
	| LCHIJA | neat                    | 1.4-17                   | Neat 1.4-17.jar                                  | None                                     |
	| LCHIJA | netherex                | 2.2.5                    | NetherEx-1.12.2-2.2.5.jar                        | None                                     |
	| LCHIJA | yurtmod                 | 9.5.2                    | NomadicTents-1.12.2-9.5.2.jar                    | None                                     |
	| LCHIJA | notes                   | 1.1.1                    | Notes-1.12-1.1.1.jar                             | None                                     |
	| LCHIJA | oreexcavation           | 1.4.150                  | OreExcavation-1.4.150.jar                        | None                                     |
	| LCHIJA | bonecraft               | 1.12.2b                  | Pam's BoneCraft 1.12.2b.jar                      | None                                     |
	| LCHIJA | clayspawn               | 1.12a                    | Pam's ClaySpawn 1.12a.jar                        | None                                     |
	| LCHIJA | getalltheseeds          | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar               | None                                     |
	| LCHIJA | simplerecipes           | 1.12.2c                  | Pam's Simple Recipes 1.12.2c.jar                 | None                                     |
	| LCHIJA | patchouli               | 1.0-23.6                 | Patchouli-1.0-23.6.jar                           | None                                     |
	| LCHIJA | pickletweaks            | 2.1.3                    | PickleTweaks-1.12.2-2.1.3.jar                    | None                                     |
	| LCHIJA | placebo                 | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCHIJA | plants2                 | 2.10.7                   | Plants-1.12.2-2.10.7.jar                         | None                                     |
	| LCHIJA | potioncore              | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                    | None                                     |
	| LCHIJA | qualitytools            | 1.0.7_for_1.12.2         | QualityTools-1.0.7_for_1.12.2.jar                | None                                     |
	| LCHIJA | quarkoddities           | 1                        | QuarkOddities-1.12.2.jar                         | None                                     |
	| LCHIJA | questbook               | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                         | None                                     |
	| LCHIJA | reccomplex              | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                     | None                                     |
	| LCHIJA | refinedstorage          | 1.6.16                   | refinedstorage-1.6.16.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | regrowth                | 0.0.0.5                  | Regrowth-1.12.2-0.0.1.1.jar                      | None                                     |
	| LCHIJA | additionalstructures    | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LCHIJA | ruins                   | 17.2                     | Ruins-1.12.2.jar                                 | None                                     |
	| LCHIJA | savemystronghold        | 1.12.2-1.0.0             | savemystronghold-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJA | sexmod                  | 1.0                      | SchnurriTV's Sexmod - 1.1.jar                    | None                                     |
	| LCHIJA | geckolib3               | 1.0                      | SchnurriTV's Sexmod - 1.1.jar                    | None                                     |
	| LCHIJA | valkyrielib             | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
	| LCHIJA | simplegenerators        | 1.12.2-2.0.20.2          | simplegenerators-1.12.2-2.0.20.2.jar             | None                                     |
	| LCHIJA | simplyjetpacks          | 1.12.2-2.2.20.0          | SimplyJetpacks2-1.12.2-2.2.20.0.jar              | None                                     |
	| LCHIJA | somanyenchantments      | 0.5.2                    | SoManyEnchantments-0.5.2.jar                     | None                                     |
	| LCHIJA | sophisticatedwolves     | 3.13.8                   | SophisticatedWolves-1.12.2-3.13.8.jar            | None                                     |
	| LCHIJA | bq_standard             | 3.4.173                  | StandardExpansion-3.4.173.jar                    | None                                     |
	| LCHIJA | storagedrawers          | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                  | None                                     |
	| LCHIJA | thebetweenlands         | 3.7.3                    | TheBetweenlands-3.7.3-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | storagedrawersunlimited | 1.12.2-1.3.0             | StorageDrawersUnlimited-1.12.2-1.3.0.jar         | None                                     |
	| LCHIJA | tameable_arachne        | 1.1.6                    | tameable_arachne_mod-1.02.jar                    | None                                     |
	| LCHIJA | toroquest               | 1.12.2-5.3               | toroquest-1.12.2-5.3.jar                         | None                                     |
	| LCHIJA | xat                     | 0.30                     | Trinkets and Baubles-0.30.1.jar                  | None                                     |
	| LCHIJA | twilightforest          | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar    | None                                     |
	| LCHIJA | ultimate_unicorn_mod    | 1.5.17                   | ultimate_unicorn_mod-1.12.2-1.5.17.jar           | None                                     |
	| LCHIJA | universalmodifiers      | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
	| LCHIJA | wailaharvestability     | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| LCHIJA | wawla                   | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones               | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                       | None                                     |
	| LCHIJA | weeeflowers             | 1.12.2b                  | Weee! Flowers 1.12.2b.jar                        | None                                     |
	| LCHIJA | recipehandler           | 0.14                     | YARCF-0.14(1.12.2).jar                           | None                                     |
	| LCHIJA | rtg                     | 6.1.0.0-snapshot.1       | RTG-1.12.2-6.1.0.0-snapshot.1.jar                | None                                     |
	| LCHIJA | mysticallib             | 1.12.2-1.11.0            | mysticallib-1.12.2-1.11.0.jar                    | None                                     |
	| UD     | mclib_core              | 2.3.5                    | minecraft.jar                                    | None                                     |

	Loaded coremods (and transformers): 
CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  svenhjol.charm.base.CharmClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.042210-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
McLib core mod (mclib-2.3.5-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Uziel25P'/12841, l='Earth', x=359.26, y=22.00, z=148.61]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14736 Compatibility Profile Context 20.11.1 27.20.12033.2007
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by firis-games** [comment]
今回の事象はMysticalWorldの影響によるものです。
こちらで対応するには対象MOD向けに個別対応を行わなければならないため対応しません。

また報告する場合は最小構成にてバグ挙動を確認の上報告して下さい。
（今回の場合であればLMRFPとMysticalWorldのみで事象が発生するなど）
