### ISSUE TITLE
Maids use sugars that is for contract as well

### ISSUE THREAD

**Issue by warning-djkajslh** [firis-games/LittleMaidReengagedFirisPatch#81]
Issue:
I put sugars into maid's skirt for it to extend the contract, but it then eat the sugars to heal itself instead
There is no way to divide between healing sugar and contracting sugar
Solution:

- [ ] Make a new inventory slot that is used solely for contracting sugar, healing sugars go in maid's inventory
- [ ] Allow maids to heal from more foods, such eat pumpkin pies, bread, cake and even meat when placed in their inventory

**Comment by firis-games** [comment]
砂糖の根本的な変更は本MODに対する影響が大きいので対応しません。
砂糖以外を砂糖として扱う方法は既に提供しています。
lmreengaged.cfgのS:Favorite.SugarにアイテムIDを設定すれば砂糖以外も砂糖として扱えます。
