### ISSUE TITLE
Suggestion: Add in custom skins selection for maid's Steve models

### ISSUE THREAD

**Issue by warning-djkajslh** [firis-games/LittleMaidReengagedFirisPatch#83]
Problem:
I want to use the maid's Steve model and not the default maid model.
I can't add more skins to that model, and there is no alternative way for me to do so either

Solution:
Make it so that people can add more skin for the model.

Reason:
All other different maid models are allowed to have tons of skins to them, minus the default Steve
There are a tiny amount of players that prefer to use the Steve model over maids (like me), so you should add in this fuction for them.

**Comment by firis-games** [comment]
マルチモデルとマルチモデル用のスキンを作る手段は用意しているので必要であれば自分で作成して下さい。

# 参考
https://github.com/firis-games/LittleMaidReengagedFirisPatch/blob/master/LittleMaidModelProject/README.md
https://github.com/firis-games/LMLibrary/blob/master/LittleMaidResource.md
