### ISSUE TITLE
Electroblob's Wizardryを追加するとスキン選択画面が変になる

### ISSUE THREAD

**Issue by windcatc** [firis-games/LittleMaidReengagedFirisPatch#84]
いつもありがとうございます.
最初はSmoothFontとの競合が問題かと、最近モデルとかいろいろ追加して、名前見えないと探すの難しいので。MOD抜いて確認したところ[ElectroblobsWizardry-4.3.4]が原因でした。
具体的に言うと、スキン選択画面のモデル背景と右のスクロールバーが白色になって、モデルの名前の文字が二重。
一応Wizardryのほかのバージョンもテストしてみた：
4.1.4, 4.2.11 は問題ない
4.3.3, 4.3.4 は問題発生
これは向こうのBUGでしょうか？こちらでなにか設定して直る方法はありませんか？

**Comment by firis-games** [comment]
該当MODのバージョンが上がったことにより描画関連の処理が何かしら影響しおかしくなっていると思われますが、クラッシュ等していないため現状では原因特定が困難です。（LMRFPは描画関連でいろいろ独自処理を行っているため）
そのため現状では対応できません。
