### ISSUE TITLE
The Betweenlands導入時にメイドが近接攻撃でmobを倒すとクラッシュします

### ISSUE THREAD

**Issue by TukaG** [firis-games/LittleMaidReengagedFirisPatch#9]
こんにちは、いつも楽しく遊ばせて頂いています。
以前より多数のmod環境においてメイドが近接攻撃（剣と斧両方）でmobを倒すとクラッシュする現象を確認していたのですが、今回こちらで検証してみたところThe Betweenlandsというmodの導入時にそうなることが確認できました。クラッシュ後のワールド読み込みは可能で、弓での攻撃も問題ありませんでした。多数mod導入環境のクラッシュレポートと検証環境でのクラッシュレポートを送付するのでご確認お願いします。他modの競合の話となり大変申し訳ないのですがよろしくお願いします。
[crash report.zip](https://github.com/firis-games/LittleMaidReengagedFirisPatch/files/4084166/crash.report.zip)

**Comment by firis-games** [comment]
The Betweenlandsとの競合でMobを倒した場合にEntityLittleMaidAvatarMPの問題でクラッシュが発生する現象の対応を行いました。
対応版はver.fp.018でリリース予定です。

commit: b52e222ce6e7ffd334287b6553258ef9eed80900

**Comment by TukaG** [comment]
早急な対応ありがとうございます！
